const continents = [
    'Africa', 'Asia', 'Caribbean', 'East Asia', 'Europe', 'Latin America', 'Middle East',
    'North America', 'Oceiana', 'South Asia', 'United Kingdom'
]

const countries = {
    'Africa': [
        'SOUTH AFRICA',
        'NIGERIA',
        'CANADA',
        'UGANDA',
        'TANZANIA',
        'ISRAEL',
        'SPANISH',
        'Camarillo, CA 93012',
        'ETHIOPIA',
        'KENYA',
        'GHANA',
        'SWITZERLAND',
        'ZAMBIA',
        'FRANCE',
        'DENMARK',
        'Duzi-uMngeni Conservation Trust',
        'AMERICA',
        'EGYPT',
        'LEBANON',
        'ENGHLISH',
        'ESWATNI',
        'UNITED KINGDOM',
        'FRENCH',
        'BOTSWANA',
        'JORDAN',
        'TURKEY'
    ],
    'Asia': [
        'INDIA', 'HONG KONG',
        'TAIWAN', 'CHINA',
        'KOREA, REPUBLIC OF', 'AMERICA',
        'MALAYSIA', 'THAILAND',
        'NEPAL', 'JAPAN',
        'FRANCE', 'PAKISTAN',
        'BELGIUM', 'SINGAPORE',
        'ISRAEL'
    ],
    'Caribbean': [
        'PANAMA',
        'BAHAMAS',
        'COSTA RICA',
        'GUATEMALA',
        'CANADA',
        'MEXICO',
        'DOMINICAN REPUBLIC',
        'HONDURAS',
        'NICARAGUA',
        'SINE ESUTA AND SABA'
    ], 'East Asia': [
        'INDIA', 'SINGAPORE',
        'THAILAND', 'HONG KONG',
        'JAPAN', 'BANGLADESH',
        'none', 'TAIWAN',
        'CHINA', 'AMERICA',
        'KONG', 'AUSTRALIA',
        'PHILIPPINES', 'HONGKONG',
        'VIETNAM', 'PAKISTAN',
        'MALAYSIA', 'CAMBODIA',
        'KINGDOM', 'INDONESIA',
        'KOREA,REPUBLIC OF', 'OF',
        'SRI LANKA', 'NEPAL',
        'MYANMAR', 'CANADA'
    ],
    'Europe': [
        'CANADA', 'UNITED KINGDOM', 'SPAIN',
        'FRANCE', 'NETHERLANDS', 'IRELAND',
        'BELGIUM', 'ITALY', 'BULGARIA',
        'GERMANY', 'POLAND', 'ROMANIA',
        'PORTUGAL', 'SWITZERLAND', 'FINLAND',
        'AUSTRIA', 'NORWAY', 'BELARUS',
        'CZECHIA', 'TURKEY', 'DENMARK',
        'UKRAINE', 'LUXEMBOURG', 'REPUBLIC)',
        'HUNGARY', 'GREECE', 'ESTONIA',
        'SWEDEN', 'ZEALAND', 'MALTA',
        'SERBIA', 'NY 10017', 'SLOVENIA',
        'HRVATSKA)'
    ],
    'Latin America': [
        'PANAMA',
        'COSTA RICA',
        'GUATEMALA',
        'CANADA',
        'MEXICO',
        'DOMINICAN REPUBLIC',
        'BAHAMAS',
        'SINT EUSTATIOUS AND SABA'
    ], 'Middle East': [
        'RUSSIA',
        'PAKISTAN',
        'ENGLISH',
        'UNITED KINGDOM',
        'RUSSIAN',
        'UKARINE',
        'USA',
        'KAZAKHSTAN',
        'KYGYZTAN'
    ],
    'North America': [
        'USA',
        'CANADA',
        'MEXICO',
        'ENGLISH',
        'AUSTRALIA',
        'FRENCH',
        'COSTA RICA'
    ],
    'Oceiana': ['AUSTRALIA', 'NEW ZEALAND', 'FIJI', 'N/A'],
    'South Asia': [
        'INDIA', 'SINGAPORE',
        'THAILAND', 'HONG KONG',
        'JAPAN', 'BANGLADESH',
        'TAIWAN',
        'CHINA', 'AMERICA',
        'KONG', 'AUSTRALIA',
        'PHILIPPINES', 'HONGKONG',
        'VIETNAM', 'PAKISTAN',
        'MALAYSIA', 'CAMBODIA',
        'KINGDOM', 'INDONESIA',
        'KOREA,REPUBLIC OF', 'OF',
        'SRI LANKA', 'NEPAL',
        'MYANMAR', 'CANADA'
    ], 'United Kingdom': ['United Kingdom']
}

const all_countries = [
    'SOUTH AFRICA',
        'NIGERIA',
        'CANADA',
        'UGANDA',
        'TANZANIA',
        'ISRAEL',
        'SPANISH',
        'Camarillo, CA 93012',
        'ETHIOPIA',
        'KENYA',
        'GHANA',
        'SWITZERLAND',
        'ZAMBIA',
        'FRANCE',
        'DENMARK',
        'Duzi-uMngeni Conservation Trust',
        'AMERICA',
        'EGYPT',
        'LEBANON',
        'ENGHLISH',
        'ESWATNI',
        'UNITED KINGDOM',
        'FRENCH',
        'BOTSWANA',
        'JORDAN',
        'TURKEY',
        'INDIA', 'HONG KONG',
        'TAIWAN', 'CHINA',
        'KOREA, REPUBLIC OF', 'AMERICA',
        'MALAYSIA', 'THAILAND',
        'NEPAL', 'JAPAN',
        'FRANCE', 'PAKISTAN',
        'BELGIUM', 'SINGAPORE',
        'ISRAEL',
        'PANAMA',
        'BAHAMAS',
        'COSTA RICA',
        'GUATEMALA',
        'CANADA',
        'MEXICO',
        'DOMINICAN REPUBLIC',
        'HONDURAS',
        'NICARAGUA',
        'SINE ESUTA AND SABA',
        'PANAMA',
        'BAHAMAS',
        'COSTA RICA',
        'GUATEMALA',
        'CANADA',
        'MEXICO',
        'DOMINICAN REPUBLIC',
        'HONDURAS',
        'NICARAGUA',
        'SINE ESUTA AND SABA',
        'INDIA', 'SINGAPORE',
        'THAILAND', 'HONG KONG',
        'JAPAN', 'BANGLADESH',
        'none', 'TAIWAN',
        'CHINA', 'AMERICA',
        'KONG', 'AUSTRALIA',
        'PHILIPPINES', 'HONGKONG',
        'VIETNAM', 'PAKISTAN',
        'MALAYSIA', 'CAMBODIA',
        'KINGDOM', 'INDONESIA',
        'KOREA,REPUBLIC OF', 'OF',
        'SRI LANKA', 'NEPAL',
        'MYANMAR', 'CANADA',
        'CANADA', 'UNITED KINGDOM', 'SPAIN',
        'FRANCE', 'NETHERLANDS', 'IRELAND',
        'BELGIUM', 'ITALY', 'BULGARIA',
        'GERMANY', 'POLAND', 'ROMANIA',
        'PORTUGAL', 'SWITZERLAND', 'FINLAND',
        'AUSTRIA', 'NORWAY', 'BELARUS',
        'CZECHIA', 'TURKEY', 'DENMARK',
        'UKRAINE', 'LUXEMBOURG', 'REPUBLIC)',
        'HUNGARY', 'GREECE', 'ESTONIA',
        'SWEDEN', 'ZEALAND', 'MALTA',
        'SERBIA', 'NY 10017', 'SLOVENIA',
        'PANAMA',
        'COSTA RICA',
        'GUATEMALA',
        'CANADA',
        'MEXICO',
        'DOMINICAN REPUBLIC',
        'BAHAMAS',
        'SINT EUSTATIOUS AND SABA',
        'RUSSIA',
        'PAKISTAN',
        'ENGLISH',
        'UNITED KINGDOM',
        'RUSSIAN',
        'UKARINE',
        'USA',
        'KAZAKHSTAN',
        'KYGYZTAN',
        'USA',
        'CANADA',
        'MEXICO',
        'ENGLISH',
        'AUSTRALIA',
        'FRENCH',
        'COSTA RICA',
        'AUSTRALIA', 'NEW ZEALAND', 'FIJI', 'N/A',
        'INDIA', 'SINGAPORE',
        'THAILAND', 'HONG KONG',
        'JAPAN', 'BANGLADESH',
        'TAIWAN',
        'CHINA', 'AMERICA',
        'KONG', 'AUSTRALIA',
        'PHILIPPINES', 'HONGKONG',
        'VIETNAM', 'PAKISTAN',
        'MALAYSIA', 'CAMBODIA',
        'KINGDOM', 'INDONESIA',
        'KOREA,REPUBLIC OF', 'OF',
        'SRI LANKA', 'NEPAL',
        'MYANMAR', 'CANADA','United Kingdom'
]

export {continents,countries,all_countries}